### ISSUE TITLE
Trying the command "reflex run --help" gives an error:

### ISSUE THREAD

**Issue by cbiqih** [reflex-dev/reflex-web#1108]
```
Traceback (most recent call last):
  File "/opt/virtualenvs/jupyter/bin/reflex", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/virtualenvs/jupyter/lib/python3.12/site-packages/typer/main.py", line 340, in __call__
    raise e
  File "/opt/virtualenvs/jupyter/lib/python3.12/site-packages/typer/main.py", line 323, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/virtualenvs/jupyter/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/virtualenvs/jupyter/lib/python3.12/site-packages/typer/core.py", line 738, in main
    return _main(
           ^^^^^^
  File "/opt/virtualenvs/jupyter/lib/python3.12/site-packages/typer/core.py", line 197, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/virtualenvs/jupyter/lib/python3.12/site-packages/click/core.py", line 1686, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/virtualenvs/jupyter/lib/python3.12/site-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "/opt/virtualenvs/jupyter/lib/python3.12/site-packages/click/core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/virtualenvs/jupyter/lib/python3.12/site-packages/click/core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/virtualenvs/jupyter/lib/python3.12/site-packages/click/core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/virtualenvs/jupyter/lib/python3.12/site-packages/click/core.py", line 1300, in show_help
    echo(ctx.get_help(), color=ctx.color)
         ^^^^^^^^^^^^^^
  File "/opt/virtualenvs/jupyter/lib/python3.12/site-packages/click/core.py", line 704, in get_help
    return self.command.get_help(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/virtualenvs/jupyter/lib/python3.12/site-packages/click/core.py", line 1325, in get_help
    self.format_help(ctx, formatter)
  File "/opt/virtualenvs/jupyter/lib/python3.12/site-packages/typer/core.py", line 688, in format_help
    return super().format_help(ctx, formatter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/virtualenvs/jupyter/lib/python3.12/site-packages/click/core.py", line 1358, in format_help
    self.format_options(ctx, formatter)
  File "/opt/virtualenvs/jupyter/lib/python3.12/site-packages/typer/core.py", line 654, in format_options
    _typer_format_options(self, ctx=ctx, formatter=formatter)
  File "/opt/virtualenvs/jupyter/lib/python3.12/site-packages/typer/core.py", line 578, in _typer_format_options
    rv = param.get_help_record(ctx)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/virtualenvs/jupyter/lib/python3.12/site-packages/typer/core.py", line 565, in get_help_record
    extra_str = rich.markup.escape(extra_str).strip()
                ^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'markup'
```

**Comment by Lendemor** [comment]
Can't reproduce.
