### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex-web#135]
```console
masenf@minicone reflex-web % python3.11 -m venv ../VENV-reflex-web
masenf@minicone reflex-web % . ../VENV-reflex-web/bin/activate             
(VENV-reflex-web) masenf@minicone reflex-web % pip install -e ../reflex -r requirements.txt
Successfully installed Mako-1.2.4 MarkupSafe-2.1.3 Pillow-9.5.0 SQLAlchemy-1.4.41 aiohttp-3.8.4 aiosignal-1.3.1 alembic-1.11.1 anyio-3.7.1 async-timeout-4.0.2 attrs-23.1.0 bidict-0.22.1 black-22.12.0 certifi-2023.5.7 charset-normalizer-3.2.0 click-8.1.5 cloudpickle-2.2.1 dnspython-2.3.0 email-validator-1.3.0 fastapi-0.96.1 frozenlist-1.4.0 googletrans-py-4.0.0 gunicorn-20.1.0 h11-0.14.0 h2-4.1.0 hpack-4.0.0 httpcore-0.16.3 httpx-0.23.3 hyperframe-6.0.1 idna-3.4 jinja2-3.1.2 markdown-it-py-3.0.0 mdurl-0.1.2 multidict-6.0.4 mypy-extensions-1.0.0 numpy-1.25.1 openai-0.27.8 packaging-23.1 pandas-1.5.3 pathspec-0.11.1 patsy-0.5.3 platformdirs-3.9.0 plotly-5.15.0 plotly-express-0.4.1 psutil-5.9.5 psycopg2-binary-2.9.5 pydantic-1.10.11 pygments-2.15.1 python-dateutil-2.8.2 python-dotenv-0.13.0 python-engineio-4.5.1 python-multipart-0.0.5 python-socketio-5.8.0 pytz-2023.3 redis-4.6.0 reflex-0.2.0 requests-2.31.0 rfc3986-1.5.0 rich-13.4.2 scipy-1.11.1 six-1.16.0 sniffio-1.3.0 sqlalchemy2-stubs-0.0.2a35 sqlmodel-0.0.8 starlette-0.27.0 starlette-admin-0.9.0 statsmodels-0.14.0 tenacity-8.2.2 tqdm-4.65.0 typer-0.4.2 typesense-0.14.0 typing-extensions-4.7.1 urllib3-2.0.3 uvicorn-0.20.0 watchdog-2.3.1 watchfiles-0.19.0 websockets-10.4 yarl-1.9.2

[notice] A new release of pip is available: 23.1.2 -> 23.2
[notice] To update, run: pip install --upgrade pip
(VENV-reflex-web) masenf@minicone reflex-web % reflex init
────────────────────────────────────────────────────── Initializing reflex_web ───────────────────────────────────────────────────────
[14:46:28] Initializing the web directory.                                                                               console.py:30
           Finished Initializing: reflex_web                                                                             console.py:30
(VENV-reflex-web) masenf@minicone reflex-web % reflex run
──────────────────────────────────────────────────────── Starting Reflex App ─────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/Users/masenf/code/pynecone-io/VENV-reflex-web/bin/reflex", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/masenf/code/pynecone-io/VENV-reflex-web/lib/python3.11/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masenf/code/pynecone-io/VENV-reflex-web/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masenf/code/pynecone-io/VENV-reflex-web/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/masenf/code/pynecone-io/VENV-reflex-web/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masenf/code/pynecone-io/VENV-reflex-web/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masenf/code/pynecone-io/VENV-reflex-web/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masenf/code/pynecone-io/VENV-reflex-web/lib/python3.11/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masenf/code/pynecone-io/pynecone/reflex/reflex.py", line 129, in run
    app = prerequisites.get_app()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masenf/code/pynecone-io/pynecone/reflex/utils/prerequisites.py", line 108, in get_app
    return __import__(module, fromlist=(constants.APP_VAR,))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masenf/code/pynecone-io/reflex-web/pcweb/pcweb.py", line 8, in <module>
    from pcweb.pages import routes
  File "/Users/masenf/code/pynecone-io/reflex-web/pcweb/pages/__init__.py", line 3, in <module>
    from .blog import *
  File "/Users/masenf/code/pynecone-io/reflex-web/pcweb/pages/blog/__init__.py", line 1, in <module>
    from .blog import *
  File "/Users/masenf/code/pynecone-io/reflex-web/pcweb/pages/blog/blog.py", line 5, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by FHU-yezi** [comment]
Try this:

```bash
pip install PyYAML
```
