### ISSUE TITLE
Failed to run

### ISSUE THREAD

**Issue by andypangaribuan** [reflex-dev/reflex-web#388]
error when run the project.

1. clone the reflex-web (main branch)
2. python3 -m venv venv
3. source venv/bin/activate
4. python -m pip install -r requirements.txt
5. reflex init
6. reflex run

then error "AttributeError: module 'reflex' has no attribute reflex.radix"

```
Traceback (most recent call last):
  File "/Users/apangaribuan/all/github/reflex-web/venv/bin/reflex", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/apangaribuan/all/github/reflex-web/venv/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/Users/apangaribuan/all/github/reflex-web/venv/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apangaribuan/all/github/reflex-web/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apangaribuan/all/github/reflex-web/venv/lib/python3.11/site-packages/typer/core.py", line 778, in main
    return _main(
           ^^^^^^
  File "/Users/apangaribuan/all/github/reflex-web/venv/lib/python3.11/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/apangaribuan/all/github/reflex-web/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apangaribuan/all/github/reflex-web/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apangaribuan/all/github/reflex-web/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apangaribuan/all/github/reflex-web/venv/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apangaribuan/all/github/reflex-web/venv/lib/python3.11/site-packages/reflex/reflex.py", line 250, in run
    _run(env, frontend, backend, frontend_port, backend_port, backend_host, loglevel)
  File "/Users/apangaribuan/all/github/reflex-web/venv/lib/python3.11/site-packages/reflex/reflex.py", line 181, in _run
    prerequisites.get_compiled_app()
  File "/Users/apangaribuan/all/github/reflex-web/venv/lib/python3.11/site-packages/reflex/utils/prerequisites.py", line 181, in get_compiled_app
    app_module = get_app(reload=reload)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apangaribuan/all/github/reflex-web/venv/lib/python3.11/site-packages/reflex/utils/prerequisites.py", line 160, in get_app
    app = __import__(module, fromlist=(constants.CompileVars.APP,))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apangaribuan/all/github/reflex-web/pcweb/pcweb.py", line 6, in <module>
    from pcweb.pages import page404, routes
  File "/Users/apangaribuan/all/github/reflex-web/pcweb/pages/__init__.py", line 5, in <module>
    from .docs import doc_routes
  File "/Users/apangaribuan/all/github/reflex-web/pcweb/pages/docs/__init__.py", line 77, in <module>
    clist = [title, *[eval(c) for c in d.metadata["components"]]]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apangaribuan/all/github/reflex-web/pcweb/pages/docs/__init__.py", line 77, in <listcomp>
    clist = [title, *[eval(c) for c in d.metadata["components"]]]
                      ^^^^^^^
  File "<string>", line 1, in <module>
  File "/Users/apangaribuan/all/github/reflex-web/venv/lib/python3.11/site-packages/reflex/__init__.py", line 352, in __getattr__
    raise AttributeError(f"module 'reflex' has no attribute {name}") from None
AttributeError: module 'reflex' has no attribute reflex.radix
```

please help

**Comment by ElijahAhianyo** [comment]
the right namespace is `import reflex.components.radix.themes as rdxt`

**Comment by ElijahAhianyo** [comment]
> > the right namespace is `import reflex.components.radix.themes as rdxt`
> 
> which file and line?

Ah this is an oversight on my part, I assumed you were running your reflex app. What version of reflex are you running against reflex-web? Im running this against the main branch of reflex and it runs without the error

**Comment by andypangaribuan** [comment]
@ElijahAhianyo reflex version 0.3.8, and using reflex-web main branch

**Comment by ElijahAhianyo** [comment]
> @ElijahAhianyo reflex version 0.3.8, and using reflex-web main branch

can you try running with the pre-release (`reflex==0.3.9a3`)?

**Comment by andypangaribuan** [comment]
> > @ElijahAhianyo reflex version 0.3.8, and using reflex-web main branch
> 
> can you try running with the pre-release (`reflex==0.3.9a3`)?

it's work @ElijahAhianyo 
thank you

**Comment by andypangaribuan** [comment]
solution: change to `reflex==0.3.9a3`
