### ISSUE TITLE
Cannot open the docs locally using "pc run"

### ISSUE THREAD

**Issue by Fanisting** [reflex-dev/reflex-web#46]
When I run "pc run" after "pc init", I got the unexpected errors:

```
[WARNING] We strongly advise you to use Windows Subsystem for Linux (WSL) for optimal performance when using Pynecone. Due to compatibility issues with one of our dependencies, Bun,
you may experience slower performance on Windows. By using WSL, you can expect to see a significant speed increase.
─────────────────────────────────────────────────────────────────────────────── Starting Pynecone App ───────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\OneDrive - zju.edu.cn\Python Projects\Pynecone Projects\pc_env\Scripts\pc.exe\__main__.py", line 7, in <module>
  File "E:\OneDrive - zju.edu.cn\Python Projects\Pynecone Projects\pc_env\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "E:\OneDrive - zju.edu.cn\Python Projects\Pynecone Projects\pc_env\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "E:\OneDrive - zju.edu.cn\Python Projects\Pynecone Projects\pc_env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "E:\OneDrive - zju.edu.cn\Python Projects\Pynecone Projects\pc_env\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\OneDrive - zju.edu.cn\Python Projects\Pynecone Projects\pc_env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\OneDrive - zju.edu.cn\Python Projects\Pynecone Projects\pc_env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "E:\OneDrive - zju.edu.cn\Python Projects\Pynecone Projects\pc_env\lib\site-packages\typer\main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "E:\OneDrive - zju.edu.cn\Python Projects\Pynecone Projects\pc_env\lib\site-packages\pynecone\pc.py", line 104, in run
    app = utils.get_app()
  File "E:\OneDrive - zju.edu.cn\Python Projects\Pynecone Projects\pc_env\lib\site-packages\pynecone\utils.py", line 373, in get_app
    return __import__(module, fromlist=(constants.APP_VAR,))
  File "E:\OneDrive - zju.edu.cn\Python Projects\Pynecone Projects\pcweb\pcweb\pcweb.py", line 33, in <module>
    multi_docs(path=path, component_list=component_group).component,
  File "E:\OneDrive - zju.edu.cn\Python Projects\Pynecone Projects\pcweb\pcweb\pages\docs\component.py", line 371, in multi_docs
    components = [component_docs(component) for component in component_list]
  File "E:\OneDrive - zju.edu.cn\Python Projects\Pynecone Projects\pcweb\pcweb\pages\docs\component.py", line 371, in <listcomp>
    components = [component_docs(component) for component in component_list]
  File "E:\OneDrive - zju.edu.cn\Python Projects\Pynecone Projects\pcweb\pcweb\pages\docs\component.py", line 249, in component_docs
    if len(src.get_props()) > 0:
  File "E:\OneDrive - zju.edu.cn\Python Projects\Pynecone Projects\pcweb\pcweb\pages\docs\component.py", line 93, in get_props
    assert comment.startswith("#"), f"Expected comment, got {comment}"
AssertionError: Expected comment, got class Text(ChakraComponent):
    """Render a paragraph of text."""

    tag = "Text"

    # Override the tag. The default tag is `<p>`.
    as_: Var[str]
```

**Comment by picklelo** [comment]
This should work now
