### ISSUE TITLE
No module named 'flexdown'

### ISSUE THREAD

**Issue by hannes-sistemica** [reflex-dev/reflex-web#763]
I followed your installation tutorial and I am getting:

```
❯ reflex run
────────────────────────────────────────────────── Starting Reflex App ───────────────────────────────────────────────────
Traceback (most recent call last):
  File "/Users/hannes/miniconda3/bin/reflex", line 8, in <module>
    sys.exit(cli())
  File "/Users/hannes/miniconda3/lib/python3.10/site-packages/typer/main.py", line 326, in __call__
    raise e
  File "/Users/hannes/miniconda3/lib/python3.10/site-packages/typer/main.py", line 309, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/hannes/miniconda3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hannes/miniconda3/lib/python3.10/site-packages/typer/core.py", line 723, in main
    return _main(
  File "/Users/hannes/miniconda3/lib/python3.10/site-packages/typer/core.py", line 193, in _main
    rv = self.invoke(ctx)
  File "/Users/hannes/miniconda3/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hannes/miniconda3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hannes/miniconda3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/hannes/miniconda3/lib/python3.10/site-packages/typer/main.py", line 692, in wrapper
    return callback(**use_params)
  File "/Users/hannes/miniconda3/lib/python3.10/site-packages/reflex/reflex.py", line 260, in run
    _run(env, frontend, backend, frontend_port, backend_port, backend_host, loglevel)
  File "/Users/hannes/miniconda3/lib/python3.10/site-packages/reflex/reflex.py", line 186, in _run
    prerequisites.get_compiled_app()
  File "/Users/hannes/miniconda3/lib/python3.10/site-packages/reflex/utils/prerequisites.py", line 276, in get_compiled_app
    app_module = get_app(reload=reload)
  File "/Users/hannes/miniconda3/lib/python3.10/site-packages/reflex/utils/prerequisites.py", line 249, in get_app
    app = __import__(module, fromlist=(constants.CompileVars.APP,))
  File "/Users/hannes/Development/geniepy/reflex-web/pcweb/pcweb.py", line 8, in <module>
    from pcweb.pages import page404, routes
  File "/Users/hannes/Development/geniepy/reflex-web/pcweb/pages/__init__.py", line 3, in <module>
    from .blog import blog_routes
  File "/Users/hannes/Development/geniepy/reflex-web/pcweb/pages/blog/__init__.py", line 1, in <module>
    from .blog import *
  File "/Users/hannes/Development/geniepy/reflex-web/pcweb/pages/blog/blog.py", line 2, in <module>
    from pcweb.templates.webpage import webpage
  File "/Users/hannes/Development/geniepy/reflex-web/pcweb/templates/__init__.py", line 1, in <module>
    from .docpage import docpage
  File "/Users/hannes/Development/geniepy/reflex-web/pcweb/templates/docpage/__init__.py", line 1, in <module>
    from .docpage import *
  File "/Users/hannes/Development/geniepy/reflex-web/pcweb/templates/docpage/docpage.py", line 6, in <module>
    import flexdown
ModuleNotFoundError: No module named 'flexdown'
```
Can you please guide me what i have done wrong?

**Comment by picklelo** [comment]
You need to run `pip install -r requirements.txt` first, then it should work.

**Comment by hannes-sistemica** [comment]
....sure - apparently it was late and my flu did the rest :D Sorry, everything works!
